version: "2.0"
nlu:
  - intent: clock
    examples: |
      - can you tell me what time it is?
      - when do we have in time?
      - what is the current time
      - what is the current time?
      - what is our current time
      - what does the clock show
      - what time is it?
      - what time is it
      - show me the time
  - intent: news
    examples: |
      - please give me a short briefing
      - brief me
      - brief me please
      - a briefing
      - give me a briefing
      - give me a short briefing
      - give me my briefing
      - can you tell me what happened in the world
      - give me news from yesterday
      - news
      - what kind of news is there
      - what are the news
      - what are the latest news
      - what is new
      - what news do you have
      - what happened today
      - what happened in the world today
      - what are the latest news
      - what are the news
      - show me the latest news
      - show me the news
      - show me the latest developments
  - intent: QnA-Creator
    examples: |
      - who created you
      - who has developed you
      - who built you
      - who has written you
      - who is your creator
  - intent: QnA-Greeting
    examples: |
      - hello
      - hello bot
      - hey
      - hi
      - greetings
      - hello bot
      - hello deltabot
  - intent: QnA-Joke
    examples: |
      - are you funny
      - are you funny?
      - tell a joke
      - tell me a joke
      - tell me the joke
      - tell me a bad joke
      - tell me rafas joke
      - tell me the grain of sand joke
      - tell me a joke
      - joke
      - do you know a joke
      - do you know grains of sand
      - what do you know about grains of sand
      - make me laugh
      - please be funny
      - I want to laugh
  - intent: QnA-State
    examples: |
      - how are you
      - what is your condition
      - how is your condition
      - everything ok so far
      - how are you doing
      - how is it going
  - intent: QnA-Tasks
    examples: |
      - help
      - what can you do
      - what can you do for me
      - what are your skills
      - help please
      - show me the help
      - help what can you do
  - intent: QnA-WhoAreYou
    examples: |
      - who are you
      - what is your name
      - do you have a name
      - how should I call you
  - intent: cleanup
    examples: |
      - please clean up the channel
      - delete all messages from me
      - clean up my messages
      - cleanup
      - clean up
  - intent: yes
    examples: |
      - yep
      - ya
      - yup
      - yes
  - intent: no
    examples: |
      - noin
      - no
      - nope
  - intent: answer
    examples: |
      - I would like to enter a new answer
      - new answer
      - new joke
      - new qna
  - intent: QnA-Good
    examples: |
      - I am well
      - then it's good
      - that is nice
      - that makes me happy
  - intent: QnA-Bad
    examples: |
      - I am not well
      - I feel bad
      - that is stupid
      - that makes me sad
  - intent: QnA-Thanks
    examples: |
      - thank you
      - thank you very much
      - good
      - you did a great job
      - I am happy with you
      - that was great
      - that worked
  - intent: choose
    examples: |
      - please distribute the people
      - random selection
      - I need an assignment again
      - do a little bit random
      - random
      - assign the teams
      - I need teams
